services:
  - type: web
    name: animaria
    env: docker
    rootDir: PetShop
    plan: free
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        value: forrajelahuella@hotmail.com
      - key: APP_URL
        sync: false
      - key: MAIL_MODO_DESARROLLO
        value: "false"
      - key: MAIL_ENVIAR_REAL
        value: "true"
      - key: JPA_DDL_AUTO
        value: update
      - key: THYMELEAF_CACHE
        value: "true"
